camera1_demo:  # Name of the node
  ros__parameters:
    camera_name: 'right_side_camera'
    camera_rate: 40

camera2_demo:  # Name of the node
  ros__parameters:
    camera_name: 'left_side_camera'
    camera_rate: 40